"""Adicionar campos de registro completo ao usuario

Revision ID: ef9f06d7025b
Revises: ae2581b6c973
Create Date: 2025-12-16 23:30:40.074951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text # Importar para executar SQL bruto

# revision identifiers, used by Alembic.
revision: str = 'ef9f06d7025b'
down_revision: Union[str, Sequence[str], None] = 'ae2581b6c973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sis_ogm_id'), table_name='sis_ogm')
    op.drop_table('sis_ogm')
    op.drop_index(op.f('ix_licitacoes_acompanhamento_id'), table_name='licitacoes_acompanhamento')
    op.drop_index(op.f('ix_licitacoes_acompanhamento_id_externo'), table_name='licitacoes_acompanhamento')
    op.drop_index(op.f('ix_licitacoes_acompanhamento_user_id'), table_name='licitacoes_acompanhamento')
    op.drop_table('licitacoes_acompanhamento')
    op.drop_table('progresso_coleta')
    op.alter_column('acompanhamento', 'data_acompanhamento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_acompanhamento_id'), 'acompanhamento', ['id'], unique=False)
    op.drop_index(op.f('idx_itens_busca_otimizada'), table_name='licitacoes_itens')
    op.drop_index(op.f('idx_itens_order_cover'), table_name='licitacoes_itens', postgresql_include=['descricao', 'valor_unitario', 'quantidade'])
    op.drop_index(op.f('idx_itens_order_limit'), table_name='licitacoes_itens')
    op.drop_index(op.f('idx_licitacoes_itens_descricao_tsvector'), table_name='licitacoes_itens', postgresql_using='gin')
    op.drop_column('licitacoes_itens', 'unidade_medida')
    op.drop_column('licitacoes_itens', 'numero_item')
    op.drop_column('licitacoes_itens', 'conteudo_item_json')
    op.drop_column('licitacoes_itens', 'criterio_julgamento')
    op.drop_column('licitacoes_itens', 'valor_total')
    op.alter_column('licitacoes_raw', 'pncp_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('licitacoes_raw', 'data_publicacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_licitacoes_raw_conteudo_json_gin'), table_name='licitacoes_raw', postgresql_using='gin')
    op.drop_index(op.f('idx_raw_filtros_composto'), table_name='licitacoes_raw')
    op.drop_column('licitacoes_raw', 'data_coleta')
    op.drop_column('licitacoes_raw', 'orgao_nome')
    op.drop_column('licitacoes_raw', 'sistema_origem')
    op.add_column('usuarios', sa.Column('nome_completo', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('telefone', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('cargo', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('cpf', sa.String(), nullable=True)) # CRÍTICO: nullable=True    op.create_unique_constraint(None, 'usuarios', ['cpf'])
    # ----------------------------------------------------
    # FASE 2: PREENCHIMENTO E GARANTIA DE UNICIDADE
    # ----------------------------------------------------
    
    # 2a. Preencher campos NOT NULL com valor padrão ('USUARIO_ANTIGO')
    op.execute(
        text("UPDATE usuarios SET nome_completo = 'USUARIO_ANTIGO', telefone = '(00) 00000-0000' WHERE nome_completo IS NULL OR telefone IS NULL")
    )

    # 2b. Preencher CPF com valor ÚNICO (CPF + ID)
    # Isso garante que todas as linhas antigas tenham um valor único temporário (CPF-1, CPF-2, etc.)
    op.execute(
        text("UPDATE usuarios SET cpf = 'MIGRADO-' || usuarios.id::text WHERE cpf IS NULL")
    )

    # ----------------------------------------------------
    # FASE 3: APLICAR REGRAS DE INTEGRIDADE
    # ----------------------------------------------------
    
    # 3a. Aplicar NOT NULL às colunas preenchidas
    op.alter_column('usuarios', 'nome_completo', nullable=False)
    op.alter_column('usuarios', 'telefone', nullable=False)
    
    # 3b. Aplicar UNIQUE e NOT NULL ao CPF
    op.alter_column('usuarios', 'cpf', nullable=False)
    op.create_unique_constraint(op.f('uq_usuarios_cpf'), 'usuarios', ['cpf'])
    
    # Opcional: Remover os defaults temporários se forem problemáticos
    # op.alter_column('usuarios', 'nome_completo', server_default=None) 


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'cargo')
    op.drop_column('usuarios', 'cpf')
    op.drop_column('usuarios', 'telefone')
    op.drop_column('usuarios', 'nome_completo')
    op.add_column('licitacoes_raw', sa.Column('sistema_origem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('licitacoes_raw', sa.Column('orgao_nome', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('licitacoes_raw', sa.Column('data_coleta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_raw_filtros_composto'), 'licitacoes_raw', ['sistema_origem', 'codigo_modalidade'], unique=False)
    op.create_index(op.f('idx_licitacoes_raw_conteudo_json_gin'), 'licitacoes_raw', ['conteudo_json'], unique=False, postgresql_using='gin')
    op.alter_column('licitacoes_raw', 'data_publicacao',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('licitacoes_raw', 'pncp_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('licitacoes_itens', sa.Column('valor_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('licitacoes_itens', sa.Column('criterio_julgamento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('licitacoes_itens', sa.Column('conteudo_item_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('licitacoes_itens', sa.Column('numero_item', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('licitacoes_itens', sa.Column('unidade_medida', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_licitacoes_itens_descricao_tsvector'), 'licitacoes_itens', [sa.literal_column("to_tsvector('portuguese'::regconfig, descricao::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_itens_order_limit'), 'licitacoes_itens', [sa.literal_column('(valor_unitario * quantidade) DESC'), 'licitacao_id'], unique=False)
    op.create_index(op.f('idx_itens_order_cover'), 'licitacoes_itens', [sa.literal_column('(valor_unitario * quantidade) DESC'), 'licitacao_id'], unique=False, postgresql_include=['descricao', 'valor_unitario', 'quantidade'])
    op.create_index(op.f('idx_itens_busca_otimizada'), 'licitacoes_itens', ['licitacao_id', 'valor_unitario', 'quantidade', sa.literal_column('(valor_unitario * quantidade) DESC')], unique=False)
    op.drop_index(op.f('ix_acompanhamento_id'), table_name='acompanhamento')
    op.alter_column('acompanhamento', 'data_acompanhamento',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('progresso_coleta',
    sa.Column('codigo_modalidade', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ultima_data_publicacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('data_atualizacao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('codigo_modalidade', name=op.f('progresso_coleta_pkey'))
    )
    op.create_table('licitacoes_acompanhamento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_externo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fonte', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('objeto', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status_acompanhamento', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('data_encerramento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('valor_estimado', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('link_pncp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('anotacoes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], name=op.f('licitacoes_acompanhamento_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('licitacoes_acompanhamento_pkey'))
    )
    op.create_index(op.f('ix_licitacoes_acompanhamento_user_id'), 'licitacoes_acompanhamento', ['user_id'], unique=False)
    op.create_index(op.f('ix_licitacoes_acompanhamento_id_externo'), 'licitacoes_acompanhamento', ['id_externo'], unique=True)
    op.create_index(op.f('ix_licitacoes_acompanhamento_id'), 'licitacoes_acompanhamento', ['id'], unique=False)
    op.create_table('sis_ogm',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_sistema', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dominio_padrao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sis_ogm_pkey'))
    )
    op.create_index(op.f('idx_sis_ogm_id'), 'sis_ogm', ['id'], unique=False)
    # ### end Alembic commands ###
